### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by Justinzobel** [hyprwm/hyprland-protocols#4]
Please tag releases so OS package maintainers can package it.

**Comment by vaxerski** [comment]
Should they be packaged though? All apps that utilize the protocols embed them as a subproject?

**Comment by Justinzobel** [comment]
wayland-protocols is it's own package, why wouldn't hyprland-protocols be a package? https://src.fedoraproject.org/rpms/wayland-protocols

I tried packaging xdg-desktop-portal-hyprland from the tarball and it didn't have the hyprland-protocols in it.

**Comment by vaxerski** [comment]
If you've downloaded the github auto-generated tarball, it doesn't include subprojects. Github bug.

You'll need to clone recursively and checkout

@fufexan maybe we could copy the CI for source from hl to here too?

**Comment by fufexan** [comment]
> @fufexan maybe we could copy the CI for source from hl to here too?

We should do that.

**Comment by vaxerski** [comment]
yeah xdph needs that, then we can close this as everything will include the correct protocol ver in the tarball

**Comment by fufexan** [comment]
We could also make releases of this repo. Nix doesn't use the subprojects at all, so it would be nice to have a `hyprland-protocols` version `0.1` instead of `unstable-20xx-yy-zz`.

**Comment by vaxerski** [comment]
fair enough. Still, the tarball thing would be beneficial.

**Comment by vaxerski** [comment]
a release is done.
